### ISSUE TITLE
Async

### ISSUE THREAD

**Issue by philsturgeon** [apisyouwonthate/book-surviving-apis#3]
Generally keeping things async is pretty important for frontends, and you want to try and avoid polling. Check the documentation for websockets or web hooks/callbacks/etc so the interface can move onto the next thing, and update status as you go. Too many folks use long polling for this, and it adds load to the API, uses up their rate limit, melts the iceburgs, makes the interface feel weird, etc.

Other uses for async, slipping my brain right meow.

Webooks aint no good for frontend devs, but for backend devs for sure. It's always good to talk about how folks like facebook do it. https://developers.facebook.com/docs/graph-api/webhooks

**Comment by philsturgeon** [comment]
@zackkitzmiller ZACK! This project is coming back from the dead now I have a bit more time between treee planting projects. I am wondering if you'd like to join as a guest author because we discussed this aaages ago. Maybe take a wild stab at talking about things clients need to watch out for when trying to work with async apis (mainly restful and http/rpc but you can expand to whatever pubsub you like). This is all from the client perspective not API author perspective like the old book.

> This chapter could focus on async workflows over the network, and a little on how that happens with actual code also async, but mostly the network stuff. This chapter, but redone for a client perspective. https://github.com/apisyouwonthate/book-build-apis-2/blob/master/src/1-theory/10-async.adoc

This is less about code and more about theory but code examples are ok in whatever language you like. We'll be polyglots. Lots of Node so far.

**Comment by zackkitzmiller** [comment]
ok

**Comment by philsturgeon** [comment]
We took a first pass at it and merged it into main. @zackkitzmiller could you have a ready and get back to me with any improvements? Remember, its for the client side! I keep forgetting that.
